---
Name: a2nt-cms-niceties-base-config
---
SilverStripe\Core\Manifest\ModuleManifest:
  project: app

#SilverStripe\Admin\LeftAndMain:
#  extra_requirements_javascript:
#    - 'colymba/gridfield-bulk-editing-tools:client/dist/js/main.js'
#    - 'colymba/gridfield-bulk-editing-tools:client/lang/en.js'
#  extra_requirements_css:
#    - 'colymba/gridfield-bulk-editing-tools:client/dist/styles/main.css'

SilverStripe\Admin\LeftAndMain:
  extra_requirements_javascript:
    - 'app/client/dist/js/app_cms.js'
  extra_requirements_css:
    - 'app/client/dist/css/app_cms.css'

SilverStripe\Forms\HTMLEditor\TinyMCEConfig:
  editor_css:
    - 'app/client/dist/css/app_editor.css'

SilverLeague\IDEAnnotator\DataObjectAnnotator:
  enabled: true

SilverStripe\UserForms\Form\UserForm:
  show_labels: true
